// ============================================================================
// PIPELINE NOTIFICATIONS CRUD
// ============================================================================
// CRUD operations for the pipeline_notifications table.
// Auto-generated by trigger on deals table; this layer provides
// read/update/delete for the in-app notification UI.
// ============================================================================

import { supabase } from '../supabase';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type PipelineNotificationType =
  | 'deal_won'
  | 'deal_lost'
  | 'deal_stage_change'
  | 'deal_value_change'
  | 'deal_stale'
  | 'deal_assigned'
  | 'proposal_sent'
  | 'proposal_viewed'
  | 'proposal_accepted'
  | 'demo_provisioned'
  | 'demo_expiring'
  | 'system';

export type NotificationPriority = 'low' | 'normal' | 'high' | 'urgent';

export interface PipelineNotification {
  id: string;
  user_id: string;
  deal_id: string | null;
  organization_id: string | null;
  type: PipelineNotificationType;
  title: string;
  message: string | null;
  priority: NotificationPriority;
  is_read: boolean;
  read_at: string | null;
  is_actioned: boolean;
  actioned_at: string | null;
  delivery_channels: string[];
  delivered_via: string[];
  metadata: Record<string, unknown>;
  created_at: string;
  // Joined fields
  deal?: { id: string; name: string; stage: string } | null;
  organization?: { id: string; name: string } | null;
}

export interface GetNotificationsFilters {
  type?: PipelineNotificationType;
  priority?: NotificationPriority;
  unreadOnly?: boolean;
  limit?: number;
  offset?: number;
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/**
 * Fetch pipeline notifications for a user with optional filters.
 */
export async function getPipelineNotifications(
  userId: string,
  filters: GetNotificationsFilters = {}
): Promise<PipelineNotification[]> {
  const { type, priority, unreadOnly, limit = 30, offset = 0 } = filters;

  let query = supabase
    .from('pipeline_notifications')
    .select(`
      *,
      deal:deals(id, name, stage),
      organization:organizations(id, name)
    `)
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .range(offset, offset + limit - 1);

  if (type) query = query.eq('type', type);
  if (priority) query = query.eq('priority', priority);
  if (unreadOnly) query = query.eq('is_read', false);

  const { data, error } = await query;
  if (error) {
    console.error('Error fetching pipeline notifications:', error);
    throw error;
  }
  return (data || []) as PipelineNotification[];
}

/**
 * Get count of unread pipeline notifications for a user.
 */
export async function getPipelineUnreadCount(userId: string): Promise<number> {
  const { count, error } = await supabase
    .from('pipeline_notifications')
    .select('id', { count: 'exact', head: true })
    .eq('user_id', userId)
    .eq('is_read', false);

  if (error) {
    console.error('Error fetching unread count:', error);
    return 0;
  }
  return count || 0;
}

// ---------------------------------------------------------------------------
// Mutations
// ---------------------------------------------------------------------------

/**
 * Mark a single notification as read.
 */
export async function markPipelineNotificationRead(id: string): Promise<void> {
  const { error } = await supabase
    .from('pipeline_notifications')
    .update({ is_read: true, read_at: new Date().toISOString() })
    .eq('id', id);

  if (error) {
    console.error('Error marking notification read:', error);
    throw error;
  }
}

/**
 * Mark all notifications as read for a user.
 */
export async function markAllPipelineNotificationsRead(userId: string): Promise<void> {
  const { error } = await supabase
    .from('pipeline_notifications')
    .update({ is_read: true, read_at: new Date().toISOString() })
    .eq('user_id', userId)
    .eq('is_read', false);

  if (error) {
    console.error('Error marking all notifications read:', error);
    throw error;
  }
}

/**
 * Delete a single notification.
 */
export async function deletePipelineNotification(id: string): Promise<void> {
  const { error } = await supabase
    .from('pipeline_notifications')
    .delete()
    .eq('id', id);

  if (error) {
    console.error('Error deleting notification:', error);
    throw error;
  }
}

/**
 * Manually create a pipeline notification (for non-trigger events
 * like proposal_sent, demo_provisioned, etc.).
 */
export async function createPipelineNotification(input: {
  user_id: string;
  deal_id?: string;
  organization_id?: string;
  type: PipelineNotificationType;
  title: string;
  message?: string;
  priority?: NotificationPriority;
  metadata?: Record<string, unknown>;
}): Promise<PipelineNotification> {
  const { data, error } = await supabase
    .from('pipeline_notifications')
    .insert({
      user_id: input.user_id,
      deal_id: input.deal_id || null,
      organization_id: input.organization_id || null,
      type: input.type,
      title: input.title,
      message: input.message || null,
      priority: input.priority || 'normal',
      metadata: input.metadata || {},
    })
    .select()
    .single();

  if (error) {
    console.error('Error creating pipeline notification:', error);
    throw error;
  }
  return data as PipelineNotification;
}
